name: Manually triggered workflow
on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout bromite filters
        uses: actions/checkout@v2
        with:
          repository: bromite/filters
          path: bromite
      - run: |
          echo "e92fc1b1c75689be05c9b49624ba3c464dc0d2c7" >> VERSION
          if [[ $(git -C bromite rev-parse HEAD) = $(cat VERSION) ]]; then
            NEXT_VERSION=$(cat metadata.json | jq -r '.version'| awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
            cp bromite/filters.dat $NEXT_VERSION.filter
            vim -c "set binary" -c "%s/wcslog.js/wcslog.ts/g" -c "wq" $NEXT_VERSION.filter
            zip -9 $NEXT_VERSION.filter.zip $NEXT_VERSION.filter
            ls
          fi
      - name: Get last version
        id: last-version
        run: |
          echo "::set-output name=version::$(cat metadata.json | jq -r '.version'| awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')"
      - name: Create Pull Request
        env:
          VERSION: ${{ steps.last-version.outputs.version }}
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Release $VERSION"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "Release $VERSION"
          body: ""
          signoff: false
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
