name: Manually triggered workflow
on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Checkout bromite filters
        uses: actions/checkout@v2
        with:
          repository: bromite/filters
          path: bromite
      - run: |
          git -C bromite rev-parse HEAD
