name: Manually triggered workflow
on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout bromite filters
        uses: actions/checkout@v2
        with:
          repository: bromite/filters
          path: bromite
      - run: |
          echo "e92fc1b1c75689be05c9b49624ba3c464dc0d2c7" >> VERSION
          if [[ $(git -C bromite rev-parse HEAD) = $(cat VERSION) ]]; then
            NEXT_VERSION=$(cat metadata.json | jq -r '.version'| awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
            cp bromite/filters.dat ./$NEXT_VERSION.filter
            ls
          fi
