name: Filter management
on:
  schedule:
  - cron: "* * * * *"
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update triple banana filter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash update_filter.sh
